### ISSUE TITLE
regions overlapping RA=0 

### ISSUE THREAD

**Issue by danielgruen** [esheldon/kmeans_radec#1]
I have had difficulty to get kmeans to converge when a region in the input position catalog overlaps the RA=0 line (like DES Y1). I think this may be due to how the centers are shifted in each iteration -- taking the mean RA of a bunch of points where some are RA~360 and some are RA~0 doesn't give a good new center. 
A quick-and-dirty fix where I just shift+modulo all RA such that no contiguous area is divided by RA=0 works, but is not exactly elegant.

**Comment by esheldon** [comment]
I can think of no quick, generic solution to this sort of boundary problem, at least at the moment.

It might make sense to add a ra_shift= keyword for this purpose.

**Comment by esheldon** [comment]
Maybe one idea:

the distance calculation is correct, just not the mean position calculation.

We could temporarily rotate the entire coordinate system such that ra=180,dec=0 corresponds to a random point in the cluster, calculate the mean position in that system, then rotate back.

**Comment by cpadavis** [comment]
(I just ran into the same problem today.)

One generic (but only approximate) solution is to use cartesian coordinates for calculating the means and converting back to ra/dec for the next iteration. If your goal is to create approximately equal-sized jackknife regions and those regions are relatively small on the sky, then this is probably good enough and doesn't require the user to add an ra_shift keyword. Doing this certainly improved the convergence for me.

**Comment by erykoff** [comment]
Or, I think that Erin's solution would also work.  Choose any point in the cluster, rotate, compute mean pos, and rotate back.  This is cleverer than what I was thinking.  But we need to have this fixed soon, or else everybody is going to crash headlong into the same problem with the Y1A1 footprint.

**Comment by esheldon** [comment]
my version should work in all scenarios I think

**Comment by esheldon** [comment]
Actually, eli do I recall correctly that you have code to do this?

**Comment by erykoff** [comment]
I do not.  But I don't think you need to do a full rotation; you can just change the RAs, right?

**Comment by esheldon** [comment]
On 9/10/15, erykoff notifications@github.com wrote:

> I do not.  But I don't think you need to do a full rotation; you can just
> change the RAs, right?

Don't you do this for redmapper when you place the random set of
points down and check the mask?  If it is in IDL I can translate it.

For DES we could get away with only RA, but might as well do the full solution.
-e

## 

Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by erykoff** [comment]
I never need to compute the <ra> or <dec> of anything, so it's not a problem.  Just distances, and those are fine.

But it's not just DES that can get away with only RA.  That's the only problem!

**Comment by esheldon** [comment]
What if your cluster is sitting at a pole?

**Comment by erykoff** [comment]
I don't see the problem...I'm only computing spherical distances from one galaxy to other neighboring galaxies.  I'm assuming that the spherical-distance-computation code is correct.

**Comment by esheldon** [comment]
the issue here is finding the average position in the cluster, which will suffer at any boundary, ra or dec

**Comment by erykoff** [comment]
At no point do I compute the average position of the cluster.  That's my point!

**Comment by esheldon** [comment]
On 9/11/15, erykoff notifications@github.com wrote:

> At no point do I compute the average position of the cluster.  That's my
> point!

Mass confusion.  By cluster I mean the kmeans cluster. Daniel's issue
is that working at a boundary the cannot find the mean position of the
points in the cluster, this will fail at any kind of boundary, so we
should rotate to ra=180, dec=0, not just rotate ra.

**Comment by esheldon** [comment]
I created a branch "fixmeans" with what I think is a fix for this

I actually went to x,y,z and took the mean in that space and converted back.  This has no boundary issues, although I think it should be heavily tested because I do wonder if all the conversions are being done correctly.

please give it a try

**Comment by esheldon** [comment]
was that what you mean by "cartesion" @cpadavis  ?  I had originally interpreted your statement as "the tangent plane"

**Comment by cpadavis** [comment]
oops on the misspelling! Yeah I just converted to x-y-z, took the mean
there, and converted back. Only two points in which I differed:
1. There is no guarantee that when you take the mean in cartesian
   coordinates you end up still on the unit-radius sphere, so when I
   calculated thetamean I divided by the radius ie thetamean = arccos(zmean /
   sqrt(xmean *\* 2 + ymean *\* 2 + zmean *\* 2)). Not sure how vital this really
   is though.
2. The cartesian coordinates of the data points won't change as we iterate
   through the kmeans centers, so I calculated those in advance instead of for
   each iteration of the kmeans algorithm.

**Comment by esheldon** [comment]
good points.  Do you mind sending a pull request with these parts added?

**Comment by cpadavis** [comment]
done. haven't done a PR in a while so I hope I did it properly

**Comment by danielgruen** [comment]
The fixmeans branch works for me. Thanks!

**Comment by esheldon** [comment]
I merged chris' changes.   A quick check seemed to work; daniel can you please test this one as well?

**Comment by esheldon** [comment]
I've merged into master

**Comment by danielgruen** [comment]
Yes, this works as well. Great!
